select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL
from (
SELECT * FROM (
select
       STUDY
      ,DCMNAME
      ,DCMSUBNM
      ,SUBSETSN
      ,DOCNUM
      ,INVSITE
      ,INV
      ,PT
      ,ACCESSTS
      ,LOGINTS
      ,LSTCHGTS
      ,LOCKFLAG
      ,CPEVENT
      ,DCMDATE      SMPL_DT
      ,DCMTIME      SMPL_TM
      ,ACTEVENT
      ,SUBEVENT_NUMBER
      ,VISIT_NUMBER
      ,QUALIFYING_VALUE
      ,QUALIFYING_QUESTION
      ,LAB
      ,LABRANGE_SUBSET_NUMBER
      ,LAB_ASSIGNMENT_TYPE_CODE
      ,LAB_ID
      ,PANEL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALBUMIN_SERUM',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    ALBUMIN_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALBUMIN_SERUM',LAB_RANGE_IND,NULL),NULL))    ALBUMIN_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALBUMIN_SERUM',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    ALBUMIN_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALK_PHOS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))         ALK_PHOS_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALK_PHOS',LAB_RANGE_IND,NULL),NULL))         ALK_PHOS_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALK_PHOS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))         ALK_PHOS_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'AMYLASE_SERUM',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    AMYLASE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'AMYLASE_SERUM',LAB_RANGE_IND,NULL),NULL))    AMYLASE_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'AMYLASE_SERUM',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    AMYLASE_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BICARB_SERUM',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     BICARB_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BICARB_SERUM',LAB_RANGE_IND,NULL),NULL))     BICARB_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BICARB_SERUM',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     BICARB_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BILIRUBIN_TOTAL',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  BILIRUBIN_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BILIRUBIN_TOTAL',LAB_RANGE_IND,NULL),NULL))  BILIRUBIN_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BILIRUBIN_TOTAL',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  BILIRUBIN_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BUN',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              BUN_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BUN',LAB_RANGE_IND,NULL),NULL))              BUN_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BUN',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              BUN_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CALCIUM',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))          CALCIUM_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CALCIUM',LAB_RANGE_IND,NULL),NULL))          CALCIUM_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CALCIUM',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))          CALCIUM_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CHLORIDE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))         CHLORIDE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CHLORIDE',LAB_RANGE_IND,NULL),NULL))         CHLORIDE_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CHLORIDE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))         CHLORIDE_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CHOLESTEROL_TOTAL',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  CHOLEST_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CHOLESTEROL_TOTAL',LAB_RANGE_IND,NULL),NULL))  CHOLEST_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CHOLESTEROL_TOTAL',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  CHOLEST_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CREATININE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       CREATININE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CREATININE',LAB_RANGE_IND,NULL),NULL))       CREATININE_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CREATININE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       CREATININE_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CPK',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              CREAT_PHOS_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CPK',LAB_RANGE_IND,NULL),NULL))              CREAT_PHOS_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CPK',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              CREAT_PHOS_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'5_NUCLEOTIDASE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))   FIVE_NUCLEO_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'5_NUCLEOTIDASE',LAB_RANGE_IND,NULL),NULL))   FIVE_NUCLEO_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'5_NUCLEOTIDASE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))   FIVE_NUCLEO_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GLOBULIN',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))         GLOBULIN_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GLOBULIN',LAB_RANGE_IND,NULL),NULL))         GLOBULIN_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GLOBULIN',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))         GLOBULIN_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GLUC_FASTING',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     GLUC_FAST_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GLUC_FASTING',LAB_RANGE_IND,NULL),NULL))     GLUC_FAST_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GLUC_FASTING',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     GLUC_FAST_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GLUC_NONFASTING',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  GLUC_NFAST_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GLUC_NONFASTING',LAB_RANGE_IND,NULL),NULL))  GLUC_NFAST_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GLUC_NONFASTING',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  GLUC_NFAST_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'INORG_PHOS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       INORG_PHOS_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'INORG_PHOS',LAB_RANGE_IND,NULL),NULL))       INORG_PHOS_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'INORG_PHOS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       INORG_PHOS_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LDH',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              LDH_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LDH',LAB_RANGE_IND,NULL),NULL))              LDH_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LDH',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              LDH_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAGNESIUM',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))        MAGNESIUM_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAGNESIUM',LAB_RANGE_IND,NULL),NULL))        MAGNESIUM_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAGNESIUM',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))        MAGNESIUM_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POTASSIUM',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))        POTASSIUM_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POTASSIUM',LAB_RANGE_IND,NULL),NULL))        POTASSIUM_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POTASSIUM',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))        POTASSIUM_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SGGT',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))             SGGT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SGGT',LAB_RANGE_IND,NULL),NULL))             SGGT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SGGT',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))             SGGT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SGOT_AST',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))         SGOT_AST_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SGOT_AST',LAB_RANGE_IND,NULL),NULL))         SGOT_AST_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SGOT_AST',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))         SGOT_AST_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SGPT_ALT',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))         SGPT_ALT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SGPT_ALT',LAB_RANGE_IND,NULL),NULL))         SGPT_ALT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SGPT_ALT',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))         SGPT_ALT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SODIUM',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))           SODIUM_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SODIUM',LAB_RANGE_IND,NULL),NULL))           SODIUM_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SODIUM',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))           SODIUM_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'TOT_PROT',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))         TOTAL_PROT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'TOT_PROT',LAB_RANGE_IND,NULL),NULL))         TOTAL_PROT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'TOT_PROT',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))         TOTAL_PROT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'URIC_ACID',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))        URIC_ACID_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'URIC_ACID',LAB_RANGE_IND,NULL),NULL))        URIC_ACID_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'URIC_ACID',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))        URIC_ACID_GRADE_FUL
 from (
        SELECT A.*, NVL(B.PANEL, 0) PANEL
          FROM PP_OC_OWNER.LBALLAB A,
               (SELECT DISTINCT OC_LAB_QUESTION, PANEL
                  FROM NCI_LABTEST_MAPPING
                 WHERE FILE_ID IS NOT NULL
                   AND FIELD_NAME IS NOT NULL
                   AND OC_LAB_QUESTION IS NOT NULL
                   AND (OC_STUDY = 'ALL' OR OC_STUDY = 'THER_STD' )  ) B
         WHERE A.LPARM = B.OC_LAB_QUESTION
        )
 GROUP BY
      STUDY
     ,DCMNAME
     ,DCMSUBNM
     ,SUBSETSN
     ,DOCNUM
     ,INVSITE
     ,INV
     ,PT
     ,ACCESSTS
     ,LOGINTS
     ,LSTCHGTS
     ,LOCKFLAG
     ,CPEVENT
     ,DCMDATE
     ,DCMTIME
     ,ACTEVENT
     ,SUBEVENT_NUMBER
     ,VISIT_NUMBER
     ,QUALIFYING_VALUE
     ,QUALIFYING_QUESTION
     ,LAB
     ,LABRANGE_SUBSET_NUMBER
     ,LAB_ASSIGNMENT_TYPE_CODE
     ,LAB_ID
     ,PANEL )
  WHERE 
        ALBUMIN_FUL IS NOT NULL
     OR ALK_PHOS_FUL IS NOT NULL
     OR AMYLASE_FUL IS NOT NULL
     OR BICARB_FUL IS NOT NULL
     OR BILIRUBIN_FUL IS NOT NULL
     OR BUN_FUL IS NOT NULL
     OR CALCIUM_FUL IS NOT NULL
     OR CHLORIDE_FUL IS NOT NULL
     OR CHOLEST_FUL IS NOT NULL
     OR CREATININE_FUL IS NOT NULL
     OR CREAT_PHOS_FUL IS NOT NULL
     OR FIVE_NUCLEO_FUL IS NOT NULL
     OR GLOBULIN_FUL IS NOT NULL
     OR GLUC_FAST_FUL IS NOT NULL
     OR GLUC_NFAST_FUL IS NOT NULL
     OR INORG_PHOS_FUL IS NOT NULL
     OR LDH_FUL IS NOT NULL
     OR MAGNESIUM_FUL IS NOT NULL
     OR POTASSIUM_FUL IS NOT NULL
     OR SGGT_FUL IS NOT NULL
     OR SGOT_AST_FUL IS NOT NULL
     OR SGPT_ALT_FUL IS NOT NULL
     OR SODIUM_FUL IS NOT NULL
     OR TOTAL_PROT_FUL IS NOT NULL
     OR URIC_ACID_FUL IS NOT NULL ) A,
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B
WHERE A.STUDY = B.STUDY (+)
  AND A.PT = B.PT (+)