select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'MCH',LVALUE_FUL,NULL))          MCH_FUL 
 ,max(decode(LPARM,'MCHC',LVALUE_FUL,NULL))          MCHC_FUL 
 ,max(decode(LPARM,'MCV',LVALUE_FUL,NULL))          MCV_FUL 
 ,max(decode(LPARM,'BLEEDING_TIME',LVALUE_FUL,NULL))          BLEED_TIME_FUL 
 ,max(decode(LPARM,'CLOT_RETRACTION_SCR',LVALUE_FUL,NULL))          CLOT_RETR_FUL 
 ,max(decode(LPARM,'SEMI_QUANT',LVALUE_FUL,NULL))          SEMI_QUANT_FUL 
 ,max(decode(LPARM,'QUANTITIVE',LVALUE_FUL,NULL))          QUANT_FUL 
 ,max(decode(LPARM,'CLOTTING_TIME',LVALUE_FUL,NULL))          CLOT_TIME_FUL 
 ,max(decode(LPARM,'FDP',LVALUE_FUL,NULL))          FDP_FUL 
 ,max(decode(LPARM,'FIBRINOGEN',LVALUE_FUL,NULL))         FIBRINOGEN_FUL 
 ,max(decode(LPARM,'THROMBIN_TIME',LVALUE_FUL,NULL))         THROMB_TIM_FUL 
 ,max(decode(LPARM,'NUCLEATED_RBC',LVALUE_FUL,NULL))         NUCL_RBCS_FUL 
 ,max(decode(LPARM,'COMPLEMENT',LVALUE_FUL,NULL))         COMPLEMENT_FUL 
 ,max(decode(LPARM,'COOMBS_TEST',LVALUE_FUL,NULL))         COOMBS_TST_FUL 
 ,max(decode(LPARM,'ANF',LVALUE_FUL,NULL))         ANF_FUL 
 ,max(decode(LPARM,'TOT_SERUM_PROTEIN',LVALUE_FUL,NULL))         TOT_SER_PR_FUL 
 ,max(decode(LPARM,'ALBUMIN',LVALUE_FUL,NULL))         ALBUMIN_FUL 
 ,max(decode(LPARM,'ALPHA_1',LVALUE_FUL,NULL))         ALPHA1_FUL 
 ,max(decode(LPARM,'ALPHA_2',LVALUE_FUL,NULL))         ALPHA2_FUL 
 ,max(decode(LPARM,'BETA',LVALUE_FUL,NULL))         BETA_FUL 
 ,max(decode(LPARM,'GAMMA',LVALUE_FUL,NULL))         GAMMA_FUL 
from PP_OC_OWNER.LBRCLBRC 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+) 
UNION
select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'MCH',LVALUE_FUL,NULL))          MCH_FUL 
 ,max(decode(LPARM,'MCHC',LVALUE_FUL,NULL))          MCHC_FUL 
 ,max(decode(LPARM,'MCV',LVALUE_FUL,NULL))          MCV_FUL 
 ,max(decode(LPARM,'BLEEDING_TIME',LVALUE_FUL,NULL))          BLEED_TIME_FUL 
 ,max(decode(LPARM,'CLOT_RETRACTION_SCR',LVALUE_FUL,NULL))          CLOT_RETR_FUL 
 ,max(decode(LPARM,'SEMI_QUANT',LVALUE_FUL,NULL))          SEMI_QUANT_FUL 
 ,max(decode(LPARM,'QUANTITIVE',LVALUE_FUL,NULL))          QUANT_FUL 
 ,max(decode(LPARM,'CLOTTING_TIME',LVALUE_FUL,NULL))          CLOT_TIME_FUL 
 ,max(decode(LPARM,'FDP',LVALUE_FUL,NULL))          FDP_FUL 
 ,max(decode(LPARM,'FIBRINOGEN',LVALUE_FUL,NULL))         FIBRINOGEN_FUL 
 ,max(decode(LPARM,'THROMBIN_TIME',LVALUE_FUL,NULL))         THROMB_TIM_FUL 
 ,max(decode(LPARM,'NUCLEATED_RBC',LVALUE_FUL,NULL))         NUCL_RBCS_FUL 
 ,max(decode(LPARM,'COMPLEMENT',LVALUE_FUL,NULL))         COMPLEMENT_FUL 
 ,max(decode(LPARM,'COOMBS_TEST',LVALUE_FUL,NULL))         COOMBS_TST_FUL 
 ,max(decode(LPARM,'ANF',LVALUE_FUL,NULL))         ANF_FUL 
 ,max(decode(LPARM,'TOT_SERUM_PROTEIN',LVALUE_FUL,NULL))         TOT_SER_PR_FUL 
 ,max(decode(LPARM,'ALBUMIN',LVALUE_FUL,NULL))         ALBUMIN_FUL 
 ,max(decode(LPARM,'ALPHA_1',LVALUE_FUL,NULL))         ALPHA1_FUL 
 ,max(decode(LPARM,'ALPHA_2',LVALUE_FUL,NULL))         ALPHA2_FUL 
 ,max(decode(LPARM,'BETA',LVALUE_FUL,NULL))         BETA_FUL 
 ,max(decode(LPARM,'GAMMA',LVALUE_FUL,NULL))         GAMMA_FUL 
from PP_OC_OWNER.LBALLAB 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+) 
