select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL
from (
SELECT * FROM (
select
       STUDY
      ,DCMNAME
      ,DCMSUBNM
      ,SUBSETSN
      ,DOCNUM
      ,INVSITE
      ,INV
      ,PT
      ,ACCESSTS
      ,LOGINTS
      ,LSTCHGTS
      ,LOCKFLAG
      ,CPEVENT
      ,DCMDATE      SMPL_DT
      ,DCMTIME      SMPL_TM
      ,ACTEVENT
      ,SUBEVENT_NUMBER
      ,VISIT_NUMBER
      ,QUALIFYING_VALUE
      ,QUALIFYING_QUESTION
      ,LAB
      ,LABRANGE_SUBSET_NUMBER
      ,LAB_ASSIGNMENT_TYPE_CODE
      ,LAB_ID
      ,PANEL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LYMPHOCYTES',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))      LYMPHOCYTE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LYMPHOCYTES',LAB_RANGE_IND,NULL),NULL))      LYMPHOCYTE_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LYMPHOCYTES',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))      LYMPHOCYTE_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MEGAKARYOCYTES',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))   MEGAKARYO_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MEGAKARYOCYTES',LAB_RANGE_IND,NULL),NULL))   MEGAKARYO_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MEGAKARYOCYTES',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))   MEGAKARYO_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'METAMYELOCYTES',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))   METAMYELO_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'METAMYELOCYTES',LAB_RANGE_IND,NULL),NULL))   METAMYELO_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'METAMYELOCYTES',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))   METAMYELO_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MONOCYTES',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))        MONOCYTES_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MONOCYTES',LAB_RANGE_IND,NULL),NULL))        MONOCYTES_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MONOCYTES',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))        MONOCYTES_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOBLASTS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))      MYELOBLAST_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOBLASTS',LAB_RANGE_IND,NULL),NULL))      MYELOBLAST_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOBLASTS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))      MYELOBLAST_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOCYTES_BASOS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  MYEL_BASOS_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOCYTES_BASOS',LAB_RANGE_IND,NULL),NULL))  MYEL_BASOS_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOCYTES_BASOS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  MYEL_BASOS_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOCYTES_EOSINOS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  MYEL_EOS_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOCYTES_EOSINOS',LAB_RANGE_IND,NULL),NULL))  MYEL_EOS_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOCYTES_EOSINOS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  MYEL_EOS_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOCYTES_NEUTROS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  MYEL_NEUT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOCYTES_NEUTROS',LAB_RANGE_IND,NULL),NULL))  MYEL_NEUT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MYELOCYTES_NEUTROS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  MYEL_NEUT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'M_RATING',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))         M_RATING_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'M_RATING',LAB_RANGE_IND,NULL),NULL))         M_RATING_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'M_RATING',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))         M_RATING_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'NORMOBLASTS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))      NORMOBLAST_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'NORMOBLASTS',LAB_RANGE_IND,NULL),NULL))      NORMOBLAST_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'NORMOBLASTS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))      NORMOBLAST_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PLASMA_CELLS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     PLASMA_CEL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PLASMA_CELLS',LAB_RANGE_IND,NULL),NULL))     PLASMA_CEL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PLASMA_CELLS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     PLASMA_CEL_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYMORPHS_BASOS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  POLY_BASOS_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYMORPHS_BASOS',LAB_RANGE_IND,NULL),NULL))  POLY_BASOS_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYMORPHS_BASOS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  POLY_BASOS_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYMORPHS_EOSINOS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  POLY_EOS_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYMORPHS_EOSINOS',LAB_RANGE_IND,NULL),NULL))  POLY_EOS_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYMORPHS_EOSINOS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  POLY_EOS_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYMORPHS_NEUTROS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  POLY_NEUT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYMORPHS_NEUTROS',LAB_RANGE_IND,NULL),NULL))  POLY_NEUT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYMORPHS_NEUTROS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  POLY_NEUT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROMYELOCYTES',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    PROMYELO_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROMYELOCYTES',LAB_RANGE_IND,NULL),NULL))    PROMYELO_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROMYELOCYTES',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    PROMYELO_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PRONORMOBLASTS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))   PRONORMO_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PRONORMOBLASTS',LAB_RANGE_IND,NULL),NULL))   PRONORMO_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PRONORMOBLASTS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))   PRONORMO_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'RETICULUM_CELLS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  RETIC_CELL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'RETICULUM_CELLS',LAB_RANGE_IND,NULL),NULL))  RETIC_CELL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'RETICULUM_CELLS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  RETIC_CELL_GRADE_FUL
 from (
        SELECT A.*, NVL(B.PANEL, 0) PANEL
          FROM PP_OC_OWNER.LBALLAB A,
               (SELECT DISTINCT OC_LAB_QUESTION, PANEL
                  FROM NCI_LABTEST_MAPPING
                 WHERE FILE_ID IS NOT NULL
                   AND FIELD_NAME IS NOT NULL
                   AND OC_LAB_QUESTION IS NOT NULL
                   AND (OC_STUDY = 'ALL' OR OC_STUDY = 'THER_STD' )  ) B
         WHERE A.LPARM = B.OC_LAB_QUESTION
        )
 GROUP BY
      STUDY
     ,DCMNAME
     ,DCMSUBNM
     ,SUBSETSN
     ,DOCNUM
     ,INVSITE
     ,INV
     ,PT
     ,ACCESSTS
     ,LOGINTS
     ,LSTCHGTS
     ,LOCKFLAG
     ,CPEVENT
     ,DCMDATE
     ,DCMTIME
     ,ACTEVENT
     ,SUBEVENT_NUMBER
     ,VISIT_NUMBER
     ,QUALIFYING_VALUE
     ,QUALIFYING_QUESTION
     ,LAB
     ,LABRANGE_SUBSET_NUMBER
     ,LAB_ASSIGNMENT_TYPE_CODE
     ,LAB_ID
     ,PANEL )
  WHERE 
        LYMPHOCYTE_FUL IS NOT NULL
     OR MEGAKARYO_FUL IS NOT NULL
     OR METAMYELO_FUL IS NOT NULL
     OR MONOCYTES_FUL IS NOT NULL
     OR MYELOBLAST_FUL IS NOT NULL
     OR MYEL_BASOS_FUL IS NOT NULL
     OR MYEL_EOS_FUL IS NOT NULL
     OR MYEL_NEUT_FUL IS NOT NULL
     OR M_RATING_FUL IS NOT NULL
     OR NORMOBLAST_FUL IS NOT NULL
     OR PLASMA_CEL_FUL IS NOT NULL
     OR POLY_BASOS_FUL IS NOT NULL
     OR POLY_EOS_FUL IS NOT NULL
     OR POLY_NEUT_FUL IS NOT NULL
     OR PROMYELO_FUL IS NOT NULL
     OR PRONORMO_FUL IS NOT NULL
     OR RETIC_CELL_FUL IS NOT NULL ) A,
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B
WHERE A.STUDY = B.STUDY (+)
  AND A.PT = B.PT (+)