select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL
from (
SELECT * FROM (
select
       STUDY
      ,DCMNAME
      ,DCMSUBNM
      ,SUBSETSN
      ,DOCNUM
      ,INVSITE
      ,INV
      ,PT
      ,ACCESSTS
      ,LOGINTS
      ,LSTCHGTS
      ,LOCKFLAG
      ,CPEVENT
      ,DCMDATE      SMPL_DT
      ,DCMTIME      SMPL_TM
      ,ACTEVENT
      ,SUBEVENT_NUMBER
      ,VISIT_NUMBER
      ,QUALIFYING_VALUE
      ,QUALIFYING_QUESTION
      ,LAB
      ,LABRANGE_SUBSET_NUMBER
      ,LAB_ASSIGNMENT_TYPE_CODE
      ,LAB_ID
      ,PANEL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CALCIUM_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    CALCIUM_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CALCIUM_URINE',LAB_RANGE_IND,NULL),NULL))    CALCIUM_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CALCIUM_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    CALCIUM_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CHLORIDE_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))   CHLORIDE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CHLORIDE_URINE',LAB_RANGE_IND,NULL),NULL))   CHLORIDE_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CHLORIDE_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))   CHLORIDE_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'OSMOLALITY_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  OSMOLALITY_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'OSMOLALITY_URINE',LAB_RANGE_IND,NULL),NULL))  OSMOLALITY_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'OSMOLALITY_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  OSMOLALITY_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'OXALATE_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    OXALATE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'OXALATE_URINE',LAB_RANGE_IND,NULL),NULL))    OXALATE_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'OXALATE_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    OXALATE_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POTASSIUM_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  POTASSIUM_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POTASSIUM_URINE',LAB_RANGE_IND,NULL),NULL))  POTASSIUM_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POTASSIUM_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  POTASSIUM_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_ALBUMIN',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  PROT_ALBUM_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_ALBUMIN',LAB_RANGE_IND,NULL),NULL))  PROT_ALBUM_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_ALBUMIN',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  PROT_ALBUM_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_ALPHA_1',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  PROT_ALPH1_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_ALPHA_1',LAB_RANGE_IND,NULL),NULL))  PROT_ALPH1_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_ALPHA_1',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  PROT_ALPH1_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_ALPHA_2',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  PROT_ALPH2_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_ALPHA_2',LAB_RANGE_IND,NULL),NULL))  PROT_ALPH2_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_ALPHA_2',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  PROT_ALPH2_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_BETA',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     PROT_BETA_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_BETA',LAB_RANGE_IND,NULL),NULL))     PROT_BETA_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_BETA',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     PROT_BETA_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_GAMMA',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    PROT_GAMMA_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_GAMMA',LAB_RANGE_IND,NULL),NULL))    PROT_GAMMA_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PROTEIN_GAMMA',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    PROT_GAMMA_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SODIUM_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     SODIUM_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SODIUM_URINE',LAB_RANGE_IND,NULL),NULL))     SODIUM_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SODIUM_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     SODIUM_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'UREA_NITROGEN_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  UREA_NITRO_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'UREA_NITROGEN_URINE',LAB_RANGE_IND,NULL),NULL))  UREA_NITRO_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'UREA_NITROGEN_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  UREA_NITRO_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'URIC_ACID_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  URIC_ACID_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'URIC_ACID_URINE',LAB_RANGE_IND,NULL),NULL))  URIC_ACID_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'URIC_ACID_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  URIC_ACID_GRADE_FUL
 from (
        SELECT A.*, NVL(B.PANEL, 0) PANEL
          FROM PP_OC_OWNER.LBALLAB A,
               (SELECT DISTINCT OC_LAB_QUESTION, PANEL
                  FROM NCI_LABTEST_MAPPING
                 WHERE FILE_ID IS NOT NULL
                   AND FIELD_NAME IS NOT NULL
                   AND OC_LAB_QUESTION IS NOT NULL
                   AND (OC_STUDY = 'ALL' OR OC_STUDY = 'THER_STD' )  ) B
         WHERE A.LPARM = B.OC_LAB_QUESTION
        )
 GROUP BY
      STUDY
     ,DCMNAME
     ,DCMSUBNM
     ,SUBSETSN
     ,DOCNUM
     ,INVSITE
     ,INV
     ,PT
     ,ACCESSTS
     ,LOGINTS
     ,LSTCHGTS
     ,LOCKFLAG
     ,CPEVENT
     ,DCMDATE
     ,DCMTIME
     ,ACTEVENT
     ,SUBEVENT_NUMBER
     ,VISIT_NUMBER
     ,QUALIFYING_VALUE
     ,QUALIFYING_QUESTION
     ,LAB
     ,LABRANGE_SUBSET_NUMBER
     ,LAB_ASSIGNMENT_TYPE_CODE
     ,LAB_ID
     ,PANEL )
  WHERE 
        CALCIUM_FUL IS NOT NULL
     OR CHLORIDE_FUL IS NOT NULL
     OR OSMOLALITY_FUL IS NOT NULL
     OR OXALATE_FUL IS NOT NULL
     OR POTASSIUM_FUL IS NOT NULL
     OR PROT_ALBUM_FUL IS NOT NULL
     OR PROT_ALPH1_FUL IS NOT NULL
     OR PROT_ALPH2_FUL IS NOT NULL
     OR PROT_BETA_FUL IS NOT NULL
     OR PROT_GAMMA_FUL IS NOT NULL
     OR SODIUM_FUL IS NOT NULL
     OR UREA_NITRO_FUL IS NOT NULL
     OR URIC_ACID_FUL IS NOT NULL ) A,
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B
WHERE A.STUDY = B.STUDY (+)
  AND A.PT = B.PT (+)