select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL
from (
SELECT * FROM (
select
       STUDY
      ,DCMNAME
      ,DCMSUBNM
      ,SUBSETSN
      ,DOCNUM
      ,INVSITE
      ,INV
      ,PT
      ,ACCESSTS
      ,LOGINTS
      ,LSTCHGTS
      ,LOCKFLAG
      ,CPEVENT
      ,DCMDATE      SMPL_DT
      ,DCMTIME      SMPL_TM
      ,ACTEVENT
      ,SUBEVENT_NUMBER
      ,VISIT_NUMBER
      ,QUALIFYING_VALUE
      ,QUALIFYING_QUESTION
      ,LAB
      ,LABRANGE_SUBSET_NUMBER
      ,LAB_ASSIGNMENT_TYPE_CODE
      ,LAB_ID
      ,PANEL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALBUMIN',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))          ALBUMIN_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALBUMIN',LAB_RANGE_IND,NULL),NULL))          ALBUMIN_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALBUMIN',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))          ALBUMIN_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALPHA_1',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))          ALPHA1_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALPHA_1',LAB_RANGE_IND,NULL),NULL))          ALPHA1_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALPHA_1',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))          ALPHA1_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALPHA_2',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))          ALPHA2_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALPHA_2',LAB_RANGE_IND,NULL),NULL))          ALPHA2_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ALPHA_2',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))          ALPHA2_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ANF',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              ANF_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ANF',LAB_RANGE_IND,NULL),NULL))              ANF_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ANF',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              ANF_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BETA',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))             BETA_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BETA',LAB_RANGE_IND,NULL),NULL))             BETA_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BETA',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))             BETA_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BLEEDING_TIME',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    BLEED_TIME_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BLEEDING_TIME',LAB_RANGE_IND,NULL),NULL))    BLEED_TIME_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BLEEDING_TIME',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    BLEED_TIME_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CLOT_RETRACTION_SCR',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  CLOT_RETR_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CLOT_RETRACTION_SCR',LAB_RANGE_IND,NULL),NULL))  CLOT_RETR_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CLOT_RETRACTION_SCR',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  CLOT_RETR_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CLOTTING_TIME',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    CLOT_TIME_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CLOTTING_TIME',LAB_RANGE_IND,NULL),NULL))    CLOT_TIME_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CLOTTING_TIME',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    CLOT_TIME_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'COMPLEMENT',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       COMPLEMENT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'COMPLEMENT',LAB_RANGE_IND,NULL),NULL))       COMPLEMENT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'COMPLEMENT',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       COMPLEMENT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'COOMBS_TEST',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))      COOMBS_TST_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'COOMBS_TEST',LAB_RANGE_IND,NULL),NULL))      COOMBS_TST_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'COOMBS_TEST',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))      COOMBS_TST_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'FDP',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              FDP_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'FDP',LAB_RANGE_IND,NULL),NULL))              FDP_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'FDP',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              FDP_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'FIBRINOGEN',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       FIBRINOGEN_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'FIBRINOGEN',LAB_RANGE_IND,NULL),NULL))       FIBRINOGEN_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'FIBRINOGEN',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       FIBRINOGEN_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GAMMA',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))            GAMMA_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GAMMA',LAB_RANGE_IND,NULL),NULL))            GAMMA_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'GAMMA',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))            GAMMA_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MCH',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              MCH_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MCH',LAB_RANGE_IND,NULL),NULL))              MCH_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MCH',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              MCH_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MCHC',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))             MCHC_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MCHC',LAB_RANGE_IND,NULL),NULL))             MCHC_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MCHC',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))             MCHC_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MCV',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              MCV_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MCV',LAB_RANGE_IND,NULL),NULL))              MCV_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MCV',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              MCV_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'NUCLEATED_RBC',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    NUCL_RBCS_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'NUCLEATED_RBC',LAB_RANGE_IND,NULL),NULL))    NUCL_RBCS_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'NUCLEATED_RBC',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    NUCL_RBCS_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'QUANTITIVE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       QUANT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'QUANTITIVE',LAB_RANGE_IND,NULL),NULL))       QUANT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'QUANTITIVE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       QUANT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SEMI_QUANT',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       SEMI_QUANT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SEMI_QUANT',LAB_RANGE_IND,NULL),NULL))       SEMI_QUANT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SEMI_QUANT',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       SEMI_QUANT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'THROMBIN_TIME',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    THROMB_TIM_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'THROMBIN_TIME',LAB_RANGE_IND,NULL),NULL))    THROMB_TIM_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'THROMBIN_TIME',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    THROMB_TIM_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'TOT_SERUM_PROTEIN',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  TOT_SER_PR_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'TOT_SERUM_PROTEIN',LAB_RANGE_IND,NULL),NULL))  TOT_SER_PR_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'TOT_SERUM_PROTEIN',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  TOT_SER_PR_GRADE_FUL
 from (
        SELECT A.*, NVL(B.PANEL, 0) PANEL
          FROM PP_OC_OWNER.LBALLAB A,
               (SELECT DISTINCT OC_LAB_QUESTION, PANEL
                  FROM NCI_LABTEST_MAPPING
                 WHERE FILE_ID IS NOT NULL
                   AND FIELD_NAME IS NOT NULL
                   AND OC_LAB_QUESTION IS NOT NULL
                   AND (OC_STUDY = 'ALL' OR OC_STUDY = 'THER_STD' )  ) B
         WHERE A.LPARM = B.OC_LAB_QUESTION
        )
 GROUP BY
      STUDY
     ,DCMNAME
     ,DCMSUBNM
     ,SUBSETSN
     ,DOCNUM
     ,INVSITE
     ,INV
     ,PT
     ,ACCESSTS
     ,LOGINTS
     ,LSTCHGTS
     ,LOCKFLAG
     ,CPEVENT
     ,DCMDATE
     ,DCMTIME
     ,ACTEVENT
     ,SUBEVENT_NUMBER
     ,VISIT_NUMBER
     ,QUALIFYING_VALUE
     ,QUALIFYING_QUESTION
     ,LAB
     ,LABRANGE_SUBSET_NUMBER
     ,LAB_ASSIGNMENT_TYPE_CODE
     ,LAB_ID
     ,PANEL )
  WHERE 
        ALBUMIN_FUL IS NOT NULL
     OR ALPHA1_FUL IS NOT NULL
     OR ALPHA2_FUL IS NOT NULL
     OR ANF_FUL IS NOT NULL
     OR BETA_FUL IS NOT NULL
     OR BLEED_TIME_FUL IS NOT NULL
     OR CLOT_RETR_FUL IS NOT NULL
     OR CLOT_TIME_FUL IS NOT NULL
     OR COMPLEMENT_FUL IS NOT NULL
     OR COOMBS_TST_FUL IS NOT NULL
     OR FDP_FUL IS NOT NULL
     OR FIBRINOGEN_FUL IS NOT NULL
     OR GAMMA_FUL IS NOT NULL
     OR MCHC_FUL IS NOT NULL
     OR MCH_FUL IS NOT NULL
     OR MCV_FUL IS NOT NULL
     OR NUCL_RBCS_FUL IS NOT NULL
     OR QUANT_FUL IS NOT NULL
     OR SEMI_QUANT_FUL IS NOT NULL
     OR THROMB_TIM_FUL IS NOT NULL
     OR TOT_SER_PR_FUL IS NOT NULL ) A,
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B
WHERE A.STUDY = B.STUDY (+)
  AND A.PT = B.PT (+)