select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'HEMOGLOBIN',LVALUE_FUL,NULL))          HEMOGLOBIN_FUL 
 ,max(decode(LPARM,'HEMATOCRIT',LVALUE_FUL,NULL))          HEMATOCRIT_FUL 
 ,max(decode(LPARM,'WBC_SERUM',LVALUE_FUL,NULL))          WBC_FUL 
 ,max(decode(LPARM,'NEUT',LVALUE_FUL,NULL))          NEUTROPHIL_FUL 
 ,max(decode(LPARM,'LYMPHOCYTES_SERUM',LVALUE_FUL,NULL))          LYMPHOCYTE_FUL 
 ,max(decode(LPARM,'BASO',LVALUE_FUL,NULL))          BASOPHILS_FUL 
 ,max(decode(LPARM,'MONOCYTES_SERUM',LVALUE_FUL,NULL))          MONOCYTES_FUL 
 ,max(decode(LPARM,'EOSIN',LVALUE_FUL,NULL))          EOSINOPHIL_FUL 
 ,max(decode(LPARM,'BANDS',LVALUE_FUL,NULL))          BANDS_FUL 
 ,max(decode(LPARM,'BLAST_CELLS',LVALUE_FUL,NULL))         BLASTS_FUL 
 ,max(decode(LPARM,'A_LYMPH',LVALUE_FUL,NULL))         ATYP_LYMPH_FUL 
 ,max(decode(LPARM,'OTHR_DIFF',LVALUE_FUL,NULL))         OTHER_DIFF_FUL 
 ,max(decode(LPARM,'PLT',LVALUE_FUL,NULL))         PLATELETS_FUL 
 ,max(decode(LPARM,'ANC',LVALUE_FUL,NULL))         ANC_FUL 
 ,max(decode(LPARM,'RBC_SERUM',LVALUE_FUL,NULL))         RBC_FUL 
 ,max(decode(LPARM,'RETIC',LVALUE_FUL,NULL))         RETICULO_FUL 
 ,max(decode(LPARM,'ESR',LVALUE_FUL,NULL))         ESR_FUL 
 ,max(decode(LPARM,'PT',LVALUE_FUL,NULL))         PTIME_FUL 
 ,max(decode(LPARM,'PTT',LVALUE_FUL,NULL))         PTT_FUL 
from PP_OC_OWNER.LBHMLAB 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+) 
UNION
select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'HEMOGLOBIN',LVALUE_FUL,NULL))          HEMOGLOBIN_FUL 
 ,max(decode(LPARM,'HEMATOCRIT',LVALUE_FUL,NULL))          HEMATOCRIT_FUL 
 ,max(decode(LPARM,'WBC_SERUM',LVALUE_FUL,NULL))          WBC_FUL 
 ,max(decode(LPARM,'NEUT',LVALUE_FUL,NULL))          NEUTROPHIL_FUL 
 ,max(decode(LPARM,'LYMPHOCYTES_SERUM',LVALUE_FUL,NULL))          LYMPHOCYTE_FUL 
 ,max(decode(LPARM,'BASO',LVALUE_FUL,NULL))          BASOPHILS_FUL 
 ,max(decode(LPARM,'MONOCYTES_SERUM',LVALUE_FUL,NULL))          MONOCYTES_FUL 
 ,max(decode(LPARM,'EOSIN',LVALUE_FUL,NULL))          EOSINOPHIL_FUL 
 ,max(decode(LPARM,'BANDS',LVALUE_FUL,NULL))          BANDS_FUL 
 ,max(decode(LPARM,'BLAST_CELLS',LVALUE_FUL,NULL))         BLASTS_FUL 
 ,max(decode(LPARM,'A_LYMPH',LVALUE_FUL,NULL))         ATYP_LYMPH_FUL 
 ,max(decode(LPARM,'OTHR_DIFF',LVALUE_FUL,NULL))         OTHER_DIFF_FUL 
 ,max(decode(LPARM,'PLT',LVALUE_FUL,NULL))         PLATELETS_FUL 
 ,max(decode(LPARM,'ANC',LVALUE_FUL,NULL))         ANC_FUL 
 ,max(decode(LPARM,'RBC_SERUM',LVALUE_FUL,NULL))         RBC_FUL 
 ,max(decode(LPARM,'RETIC',LVALUE_FUL,NULL))         RETICULO_FUL 
 ,max(decode(LPARM,'ESR',LVALUE_FUL,NULL))         ESR_FUL 
 ,max(decode(LPARM,'PT',LVALUE_FUL,NULL))         PTIME_FUL 
 ,max(decode(LPARM,'PTT',LVALUE_FUL,NULL))         PTT_FUL 
from PP_OC_OWNER.LBALLAB
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+)