select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL
from (
SELECT * FROM (
select
       STUDY
      ,DCMNAME
      ,DCMSUBNM
      ,SUBSETSN
      ,DOCNUM
      ,INVSITE
      ,INV
      ,PT
      ,ACCESSTS
      ,LOGINTS
      ,LSTCHGTS
      ,LOCKFLAG
      ,CPEVENT
      ,DCMDATE      SMPL_DT
      ,DCMTIME      SMPL_TM
      ,ACTEVENT
      ,SUBEVENT_NUMBER
      ,VISIT_NUMBER
      ,QUALIFYING_VALUE
      ,QUALIFYING_QUESTION
      ,LAB
      ,LABRANGE_SUBSET_NUMBER
      ,LAB_ASSIGNMENT_TYPE_CODE
      ,LAB_ID
      ,PANEL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PH',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))               ACIDITY_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PH',LAB_RANGE_IND,NULL),NULL))               ACIDITY_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PH',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))               ACIDITY_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BASE_DEFICIT',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     BASE_DEF_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BASE_DEFICIT',LAB_RANGE_IND,NULL),NULL))     BASE_DEF_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BASE_DEFICIT',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     BASE_DEF_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BASE_EXCESS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))      BASE_EXC_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BASE_EXCESS',LAB_RANGE_IND,NULL),NULL))      BASE_EXC_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BASE_EXCESS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))      BASE_EXC_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BICARB',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))           BICARB_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BICARB',LAB_RANGE_IND,NULL),NULL))           BICARB_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BICARB',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))           BICARB_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CO',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))               CARB_MONOX_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CO',LAB_RANGE_IND,NULL),NULL))               CARB_MONOX_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CO',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))               CARB_MONOX_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'DIFFUSING_CAPACITY',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  DIFF_CAPAC_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'DIFFUSING_CAPACITY',LAB_RANGE_IND,NULL),NULL))  DIFF_CAPAC_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'DIFFUSING_CAPACITY',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  DIFF_CAPAC_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'EXPIRATORY_VOL',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))   EXP_VOL_1_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'EXPIRATORY_VOL',LAB_RANGE_IND,NULL),NULL))   EXP_VOL_1_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'EXPIRATORY_VOL',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))   EXP_VOL_1_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'FUNC_RESIDUAL_CAP',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  FUN_RES_CP_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'FUNC_RESIDUAL_CAP',LAB_RANGE_IND,NULL),NULL))  FUN_RES_CP_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'FUNC_RESIDUAL_CAP',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  FUN_RES_CP_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAX_CAPACITY',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     MAX_CAP_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAX_CAPACITY',LAB_RANGE_IND,NULL),NULL))     MAX_CAP_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAX_CAPACITY',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     MAX_CAP_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAX_FXP_FLOW',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     MAX_EXP_FL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAX_FXP_FLOW',LAB_RANGE_IND,NULL),NULL))     MAX_EXP_FL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAX_FXP_FLOW',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     MAX_EXP_FL_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'METHEMOGLOBIN',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    METHEMOGLO_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'METHEMOGLOBIN',LAB_RANGE_IND,NULL),NULL))    METHEMOGLO_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'METHEMOGLOBIN',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    METHEMOGLO_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAX_MID_FXP_FLOW',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  MID_EXP_FL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAX_MID_FXP_FLOW',LAB_RANGE_IND,NULL),NULL))  MID_EXP_FL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MAX_MID_FXP_FLOW',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  MID_EXP_FL_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'OXYGEN_SATURATION',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  OXYGEN_SAT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'OXYGEN_SATURATION',LAB_RANGE_IND,NULL),NULL))  OXYGEN_SAT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'OXYGEN_SATURATION',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  OXYGEN_SAT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PO2',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              PARTIAL_O2_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PO2',LAB_RANGE_IND,NULL),NULL))              PARTIAL_O2_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PO2',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              PARTIAL_O2_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PCO2',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))             PART_CO2_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PCO2',LAB_RANGE_IND,NULL),NULL))             PART_CO2_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PCO2',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))             PART_CO2_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PULM_COMPLIANCE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  PULM_COMPL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PULM_COMPLIANCE',LAB_RANGE_IND,NULL),NULL))  PULM_COMPL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PULM_COMPLIANCE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  PULM_COMPL_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'RESIDUAL_VOLUME',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  RESID_VOL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'RESIDUAL_VOLUME',LAB_RANGE_IND,NULL),NULL))  RESID_VOL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'RESIDUAL_VOLUME',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  RESID_VOL_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'TIDAL_VOLUME',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     TIDAL_VOL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'TIDAL_VOLUME',LAB_RANGE_IND,NULL),NULL))     TIDAL_VOL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'TIDAL_VOLUME',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     TIDAL_VOL_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'VITAL_CAPACITY',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))   VITAL_CAP_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'VITAL_CAPACITY',LAB_RANGE_IND,NULL),NULL))   VITAL_CAP_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'VITAL_CAPACITY',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))   VITAL_CAP_GRADE_FUL
 from (
        SELECT A.*, NVL(B.PANEL, 0) PANEL
          FROM PP_OC_OWNER.LBALLAB A,
               (SELECT DISTINCT OC_LAB_QUESTION, PANEL
                  FROM NCI_LABTEST_MAPPING
                 WHERE FILE_ID IS NOT NULL
                   AND FIELD_NAME IS NOT NULL
                   AND OC_LAB_QUESTION IS NOT NULL
                   AND (OC_STUDY = 'ALL' OR OC_STUDY = 'THER_STD' )  ) B
         WHERE A.LPARM = B.OC_LAB_QUESTION
        )
 GROUP BY
      STUDY
     ,DCMNAME
     ,DCMSUBNM
     ,SUBSETSN
     ,DOCNUM
     ,INVSITE
     ,INV
     ,PT
     ,ACCESSTS
     ,LOGINTS
     ,LSTCHGTS
     ,LOCKFLAG
     ,CPEVENT
     ,DCMDATE
     ,DCMTIME
     ,ACTEVENT
     ,SUBEVENT_NUMBER
     ,VISIT_NUMBER
     ,QUALIFYING_VALUE
     ,QUALIFYING_QUESTION
     ,LAB
     ,LABRANGE_SUBSET_NUMBER
     ,LAB_ASSIGNMENT_TYPE_CODE
     ,LAB_ID
     ,PANEL )
  WHERE 
        ACIDITY_FUL IS NOT NULL
     OR BASE_DEF_FUL IS NOT NULL
     OR BASE_EXC_FUL IS NOT NULL
     OR BICARB_FUL IS NOT NULL
     OR CARB_MONOX_FUL IS NOT NULL
     OR DIFF_CAPAC_FUL IS NOT NULL
     OR EXP_VOL_1_FUL IS NOT NULL
     OR FUN_RES_CP_FUL IS NOT NULL
     OR MAX_CAP_FUL IS NOT NULL
     OR MAX_EXP_FL_FUL IS NOT NULL
     OR METHEMOGLO_FUL IS NOT NULL
     OR MID_EXP_FL_FUL IS NOT NULL
     OR OXYGEN_SAT_FUL IS NOT NULL
     OR PARTIAL_O2_FUL IS NOT NULL
     OR PART_CO2_FUL IS NOT NULL
     OR PULM_COMPL_FUL IS NOT NULL
     OR RESID_VOL_FUL IS NOT NULL
     OR TIDAL_VOL_FUL IS NOT NULL
     OR VITAL_CAP_FUL IS NOT NULL ) A,
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B
WHERE A.STUDY = B.STUDY (+)
  AND A.PT = B.PT (+)