select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL
from (
SELECT * FROM (
select
       STUDY
      ,DCMNAME
      ,DCMSUBNM
      ,SUBSETSN
      ,DOCNUM
      ,INVSITE
      ,INV
      ,PT
      ,ACCESSTS
      ,LOGINTS
      ,LSTCHGTS
      ,LOCKFLAG
      ,CPEVENT
      ,DCMDATE      SMPL_DT
      ,DCMTIME      SMPL_TM
      ,ACTEVENT
      ,SUBEVENT_NUMBER
      ,VISIT_NUMBER
      ,QUALIFYING_VALUE
      ,QUALIFYING_QUESTION
      ,LAB
      ,LABRANGE_SUBSET_NUMBER
      ,LAB_ASSIGNMENT_TYPE_CODE
      ,LAB_ID
      ,PANEL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ADCC',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))             ADCC_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ADCC',LAB_RANGE_IND,NULL),NULL))             ADCC_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'ADCC',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))             ADCC_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'B_CELL_LEVEL',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     B_CELL_LEV_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'B_CELL_LEVEL',LAB_RANGE_IND,NULL),NULL))     B_CELL_LEV_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'B_CELL_LEVEL',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     B_CELL_LEV_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MACROS_CYTOSTASIS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  CYTOSTASIS_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MACROS_CYTOSTASIS',LAB_RANGE_IND,NULL),NULL))  CYTOSTASIS_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MACROS_CYTOSTASIS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  CYTOSTASIS_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MACROS_CYTOTXITY',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  CYTOTOX_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MACROS_CYTOTXITY',LAB_RANGE_IND,NULL),NULL))  CYTOTOX_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MACROS_CYTOTXITY',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  CYTOTOX_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SERUM_INTERFERON',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  INTERFERON_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SERUM_INTERFERON',LAB_RANGE_IND,NULL),NULL))  INTERFERON_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'SERUM_INTERFERON',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  INTERFERON_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LYMPHOCYTE_BLASTS',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  LYMPHOCYTE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LYMPHOCYTE_BLASTS',LAB_RANGE_IND,NULL),NULL))  LYMPHOCYTE_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LYMPHOCYTE_BLASTS',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  LYMPHOCYTE_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'NK_ACTIVITY',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))      NK_ACTIV_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'NK_ACTIVITY',LAB_RANGE_IND,NULL),NULL))      NK_ACTIV_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'NK_ACTIVITY',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))      NK_ACTIV_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PEROXIDE_GENERATION',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  PEROX_GEN_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PEROXIDE_GENERATION',LAB_RANGE_IND,NULL),NULL))  PEROX_GEN_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PEROXIDE_GENERATION',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  PEROX_GEN_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_CTL',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       T_CELL_CTL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_CTL',LAB_RANGE_IND,NULL),NULL))       T_CELL_CTL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_CTL',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       T_CELL_CTL_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_DTH',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       T_CELL_DTH_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_DTH',LAB_RANGE_IND,NULL),NULL))       T_CELL_DTH_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_DTH',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       T_CELL_DTH_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_HELPER',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))    T_CELL_HLP_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_HELPER',LAB_RANGE_IND,NULL),NULL))    T_CELL_HLP_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_HELPER',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))    T_CELL_HLP_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_SUPPRESSOR',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  T_CELL_SUP_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_SUPPRESSOR',LAB_RANGE_IND,NULL),NULL))  T_CELL_SUP_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_SUPPRESSOR',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  T_CELL_SUP_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_TOT',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       T_CELL_TOT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_TOT',LAB_RANGE_IND,NULL),NULL))       T_CELL_TOT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'T_CELL_TOT',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       T_CELL_TOT_GRADE_FUL
 from (
        SELECT A.*, NVL(B.PANEL, 0) PANEL
          FROM PP_OC_OWNER.LBALLAB A,
               (SELECT DISTINCT OC_LAB_QUESTION, PANEL
                  FROM NCI_LABTEST_MAPPING
                 WHERE FILE_ID IS NOT NULL
                   AND FIELD_NAME IS NOT NULL
                   AND OC_LAB_QUESTION IS NOT NULL
                   AND (OC_STUDY = 'ALL' OR OC_STUDY = 'THER_STD' )  ) B
         WHERE A.LPARM = B.OC_LAB_QUESTION
        )
 GROUP BY
      STUDY
     ,DCMNAME
     ,DCMSUBNM
     ,SUBSETSN
     ,DOCNUM
     ,INVSITE
     ,INV
     ,PT
     ,ACCESSTS
     ,LOGINTS
     ,LSTCHGTS
     ,LOCKFLAG
     ,CPEVENT
     ,DCMDATE
     ,DCMTIME
     ,ACTEVENT
     ,SUBEVENT_NUMBER
     ,VISIT_NUMBER
     ,QUALIFYING_VALUE
     ,QUALIFYING_QUESTION
     ,LAB
     ,LABRANGE_SUBSET_NUMBER
     ,LAB_ASSIGNMENT_TYPE_CODE
     ,LAB_ID
     ,PANEL )
  WHERE 
        ADCC_FUL IS NOT NULL
     OR B_CELL_LEV_FUL IS NOT NULL
     OR CYTOSTASIS_FUL IS NOT NULL
     OR CYTOTOX_FUL IS NOT NULL
     OR INTERFERON_FUL IS NOT NULL
     OR LYMPHOCYTE_FUL IS NOT NULL
     OR NK_ACTIV_FUL IS NOT NULL
     OR PEROX_GEN_FUL IS NOT NULL
     OR T_CELL_CTL_FUL IS NOT NULL
     OR T_CELL_DTH_FUL IS NOT NULL
     OR T_CELL_HLP_FUL IS NOT NULL
     OR T_CELL_SUP_FUL IS NOT NULL
     OR T_CELL_TOT_FUL IS NOT NULL ) A,
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B
WHERE A.STUDY = B.STUDY (+)
  AND A.PT = B.PT (+)