select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'CREATININE_CLEARANCE',LVALUE_FUL,NULL))          CREAT_CLR_FUL 
 ,max(decode(LPARM,'PH_URINE',LVALUE_FUL,NULL))          HYDROGEN_FUL 
 ,max(decode(LPARM,'SPECIFIC_GRAVITY',LVALUE_FUL,NULL))          SP_GRAVITY_FUL 
 ,max(decode(LPARM,'WBC_URINE',LVALUE_FUL,NULL))          WBCS_FUL 
 ,max(decode(LPARM,'RBC_URINE',LVALUE_FUL,NULL))          RBCS_FUL 
 ,max(decode(LPARM,'GLUCOSE',LVALUE_FUL,NULL))          GLUCOSE_FUL 
 ,max(decode(LPARM,'PROTEIN',LVALUE_FUL,NULL))          PROTEIN_FUL 
 ,max(decode(LPARM,'KETONES',LVALUE_FUL,NULL))          KETONES_FUL 
 ,max(decode(LPARM,'BILE',LVALUE_FUL,NULL))         BILE_FUL 
 ,max(decode(LPARM,'CREATININE_URINE',LVALUE_FUL,NULL))         URIN_CREAT_FUL 
 ,max(decode(LPARM,'VOLUME_URINE',LVALUE_FUL,NULL))         VOLUME_FUL 
 ,max(decode(LPARM,'COLLECTION_PERIOD',LVALUE_FUL,NULL))         COLL_PER_FUL 
from PP_OC_OWNER.LUSLBUS 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+) 
UNION
select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'CREATININE_CLEARANCE',LVALUE_FUL,NULL))          CREAT_CLR_FUL 
 ,max(decode(LPARM,'PH_URINE',LVALUE_FUL,NULL))          HYDROGEN_FUL 
 ,max(decode(LPARM,'SPECIFIC_GRAVITY',LVALUE_FUL,NULL))          SP_GRAVITY_FUL 
 ,max(decode(LPARM,'WBC_URINE',LVALUE_FUL,NULL))          WBCS_FUL 
 ,max(decode(LPARM,'RBC_URINE',LVALUE_FUL,NULL))          RBCS_FUL 
 ,max(decode(LPARM,'GLUCOSE',LVALUE_FUL,NULL))          GLUCOSE_FUL 
 ,max(decode(LPARM,'PROTEIN',LVALUE_FUL,NULL))          PROTEIN_FUL 
 ,max(decode(LPARM,'KETONES',LVALUE_FUL,NULL))          KETONES_FUL 
 ,max(decode(LPARM,'BILE',LVALUE_FUL,NULL))         BILE_FUL 
 ,max(decode(LPARM,'CREATININE_URINE',LVALUE_FUL,NULL))         URIN_CREAT_FUL 
 ,max(decode(LPARM,'VOLUME_URINE',LVALUE_FUL,NULL))         VOLUME_FUL 
 ,max(decode(LPARM,'COLLECTION_PERIOD',LVALUE_FUL,NULL))         COLL_PER_FUL 
from PP_OC_OWNER.LBALLAB 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+)