select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL
from (
SELECT * FROM (
select
       STUDY
      ,DCMNAME
      ,DCMSUBNM
      ,SUBSETSN
      ,DOCNUM
      ,INVSITE
      ,INV
      ,PT
      ,ACCESSTS
      ,LOGINTS
      ,LSTCHGTS
      ,LOCKFLAG
      ,CPEVENT
      ,DCMDATE      SMPL_DT
      ,DCMTIME      SMPL_TM
      ,ACTEVENT
      ,SUBEVENT_NUMBER
      ,VISIT_NUMBER
      ,QUALIFYING_VALUE
      ,QUALIFYING_QUESTION
      ,LAB
      ,LABRANGE_SUBSET_NUMBER
      ,LAB_ASSIGNMENT_TYPE_CODE
      ,LAB_ID
      ,PANEL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'AFP',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              AFP_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'AFP',LAB_RANGE_IND,NULL),NULL))              AFP_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'AFP',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              AFP_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA125',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))            CA125_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA125',LAB_RANGE_IND,NULL),NULL))            CA125_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA125',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))            CA125_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA15_3',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))           CA15_3_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA15_3',LAB_RANGE_IND,NULL),NULL))           CA15_3_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA15_3',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))           CA15_3_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA19_9',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))           CA19_9_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA19_9',LAB_RANGE_IND,NULL),NULL))           CA19_9_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA19_9',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))           CA19_9_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA27_29',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))          CA27_29_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA27_29',LAB_RANGE_IND,NULL),NULL))          CA27_29_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CA27_29',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))          CA27_29_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CEA',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              CEA_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CEA',LAB_RANGE_IND,NULL),NULL))              CEA_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'CEA',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              CEA_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'HBS_AG',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))           HBS_AG_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'HBS_AG',LAB_RANGE_IND,NULL),NULL))           HBS_AG_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'HBS_AG',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))           HBS_AG_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'HCG',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              HCG_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'HCG',LAB_RANGE_IND,NULL),NULL))              HCG_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'HCG',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              HCG_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'HIV',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              HIV_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'HIV',LAB_RANGE_IND,NULL),NULL))              HIV_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'HIV',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              HIV_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PREGNANCY',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))        PREGNANT_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PREGNANCY',LAB_RANGE_IND,NULL),NULL))        PREGNANT_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PREGNANCY',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))        PREGNANT_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PSA',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))              PSA_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PSA',LAB_RANGE_IND,NULL),NULL))              PSA_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'PSA',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))              PSA_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'STOOL_GUAIAC',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     STOOL_GUAIAC_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'STOOL_GUAIAC',LAB_RANGE_IND,NULL),NULL))     STOOL_GUAIAC_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'STOOL_GUAIAC',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     STOOL_GUAIAC_GRADE_FUL
 from (
        SELECT A.*, NVL(B.PANEL, 0) PANEL
          FROM PP_OC_OWNER.LBALLAB A,
               (SELECT DISTINCT OC_LAB_QUESTION, PANEL
                  FROM NCI_LABTEST_MAPPING
                 WHERE FILE_ID IS NOT NULL
                   AND FIELD_NAME IS NOT NULL
                   AND OC_LAB_QUESTION IS NOT NULL
                   AND (OC_STUDY = 'ALL' OR OC_STUDY = 'THER_STD' )  ) B
         WHERE A.LPARM = B.OC_LAB_QUESTION
        )
 GROUP BY
      STUDY
     ,DCMNAME
     ,DCMSUBNM
     ,SUBSETSN
     ,DOCNUM
     ,INVSITE
     ,INV
     ,PT
     ,ACCESSTS
     ,LOGINTS
     ,LSTCHGTS
     ,LOCKFLAG
     ,CPEVENT
     ,DCMDATE
     ,DCMTIME
     ,ACTEVENT
     ,SUBEVENT_NUMBER
     ,VISIT_NUMBER
     ,QUALIFYING_VALUE
     ,QUALIFYING_QUESTION
     ,LAB
     ,LABRANGE_SUBSET_NUMBER
     ,LAB_ASSIGNMENT_TYPE_CODE
     ,LAB_ID
     ,PANEL )
  WHERE 
        AFP_FUL IS NOT NULL
     OR CA125_FUL IS NOT NULL
     OR CA15_3_FUL IS NOT NULL
     OR CA19_9_FUL IS NOT NULL
     OR CA27_29_FUL IS NOT NULL
     OR CEA_FUL IS NOT NULL
     OR HBS_AG_FUL IS NOT NULL
     OR HCG_FUL IS NOT NULL
     OR HIV_FUL IS NOT NULL
     OR PREGNANT_FUL IS NOT NULL
     OR PSA_FUL IS NOT NULL
     OR STOOL_GUAIAC_FUL IS NOT NULL ) A,
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B
WHERE A.STUDY = B.STUDY (+)
  AND A.PT = B.PT (+)