select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'PH',LVALUE_FUL,NULL))          ACIDITY_FUL 
 ,max(decode(LPARM,'PCO2',LVALUE_FUL,NULL))          PART_CO2_FUL 
 ,max(decode(LPARM,'PO2',LVALUE_FUL,NULL))          PARTIAL_O2_FUL 
 ,max(decode(LPARM,'BICARB',LVALUE_FUL,NULL))          BICARB_FUL 
 ,max(decode(LPARM,'BASE_EXCESS',LVALUE_FUL,NULL))          BASE_EXC_FUL 
 ,max(decode(LPARM,'BASE_DEFICIT',LVALUE_FUL,NULL))          BASE_DEF_FUL 
 ,max(decode(LPARM,'OXYGEN_SATURATION',LVALUE_FUL,NULL))          OXYGEN_SAT_FUL 
 ,max(decode(LPARM,'CO',LVALUE_FUL,NULL))          CARB_MONOX_FUL 
 ,max(decode(LPARM,'METHEMOGLOBIN',LVALUE_FUL,NULL))          METHEMOGLO_FUL 
 ,max(decode(LPARM,'VITAL_CAPACITY',LVALUE_FUL,NULL))         VITAL_CAP_FUL 
 ,max(decode(LPARM,'EXPIRATORY_VOL',LVALUE_FUL,NULL))         EXP_VOL_1_FUL 
 ,max(decode(LPARM,'MAX_CAPACITY',LVALUE_FUL,NULL))         MAX_CAP_FUL 
 ,max(decode(LPARM,'RESIDUAL_VOLUME',LVALUE_FUL,NULL))         RESID_VOL_FUL 
 ,max(decode(LPARM,'TIDAL_VOLUME',LVALUE_FUL,NULL))         TIDAL_VOL_FUL 
 ,max(decode(LPARM,'FUNC_RESIDUAL_CAP',LVALUE_FUL,NULL))         FUN_RES_CP_FUL 
 ,max(decode(LPARM,'PULM_COMPLIANCE',LVALUE_FUL,NULL))         PULM_COMPL_FUL 
 ,max(decode(LPARM,'DIFFUSING_CAPACITY',LVALUE_FUL,NULL))         DIFF_CAPAC_FUL 
 ,max(decode(LPARM,'MAX_FXP_FLOW',LVALUE_FUL,NULL))         MAX_EXP_FL_FUL 
 ,max(decode(LPARM,'MAX_MID_FXP_FLOW',LVALUE_FUL,NULL))         MID_EXP_FL_FUL 
from PP_OC_OWNER.LBRFLBBG 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+) 
UNION
select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'PH',LVALUE_FUL,NULL))          ACIDITY_FUL 
 ,max(decode(LPARM,'PCO2',LVALUE_FUL,NULL))          PART_CO2_FUL 
 ,max(decode(LPARM,'PO2',LVALUE_FUL,NULL))          PARTIAL_O2_FUL 
 ,max(decode(LPARM,'BICARB',LVALUE_FUL,NULL))          BICARB_FUL 
 ,max(decode(LPARM,'BASE_EXCESS',LVALUE_FUL,NULL))          BASE_EXC_FUL 
 ,max(decode(LPARM,'BASE_DEFICIT',LVALUE_FUL,NULL))          BASE_DEF_FUL 
 ,max(decode(LPARM,'OXYGEN_SATURATION',LVALUE_FUL,NULL))          OXYGEN_SAT_FUL 
 ,max(decode(LPARM,'CO',LVALUE_FUL,NULL))          CARB_MONOX_FUL 
 ,max(decode(LPARM,'METHEMOGLOBIN',LVALUE_FUL,NULL))          METHEMOGLO_FUL 
 ,max(decode(LPARM,'VITAL_CAPACITY',LVALUE_FUL,NULL))         VITAL_CAP_FUL 
 ,max(decode(LPARM,'EXPIRATORY_VOL',LVALUE_FUL,NULL))         EXP_VOL_1_FUL 
 ,max(decode(LPARM,'MAX_CAPACITY',LVALUE_FUL,NULL))         MAX_CAP_FUL 
 ,max(decode(LPARM,'RESIDUAL_VOLUME',LVALUE_FUL,NULL))         RESID_VOL_FUL 
 ,max(decode(LPARM,'TIDAL_VOLUME',LVALUE_FUL,NULL))         TIDAL_VOL_FUL 
 ,max(decode(LPARM,'FUNC_RESIDUAL_CAP',LVALUE_FUL,NULL))         FUN_RES_CP_FUL 
 ,max(decode(LPARM,'PULM_COMPLIANCE',LVALUE_FUL,NULL))         PULM_COMPL_FUL 
 ,max(decode(LPARM,'DIFFUSING_CAPACITY',LVALUE_FUL,NULL))         DIFF_CAPAC_FUL 
 ,max(decode(LPARM,'MAX_FXP_FLOW',LVALUE_FUL,NULL))         MAX_EXP_FL_FUL 
 ,max(decode(LPARM,'MAX_MID_FXP_FLOW',LVALUE_FUL,NULL))         MID_EXP_FL_FUL 
from PP_OC_OWNER.LBALLAB
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+)