select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'PSA',LVALUE_FUL,NULL))          PSA_FUL 
 ,max(decode(LPARM,'CA125',LVALUE_FUL,NULL))          CA125_FUL 
 ,max(decode(LPARM,'CEA',LVALUE_FUL,NULL))          CEA_FUL 
 ,max(decode(LPARM,'CA19_9',LVALUE_FUL,NULL))          CA19_9_FUL 
 ,max(decode(LPARM,'CA15_3',LVALUE_FUL,NULL))          CA15_3_FUL 
 ,max(decode(LPARM,'CA27_29',LVALUE_FUL,NULL))          CA27_29_FUL 
 ,max(decode(LPARM,'AFP',LVALUE_FUL,NULL))          AFP_FUL 
 ,max(decode(LPARM,'HCG',LVALUE_FUL,NULL))          HCG_FUL 
 ,max(decode(LPARM,'HIV',LVALUE_FUL,NULL))          HIV_FUL 
 ,max(decode(LPARM,'HBS_AG',LVALUE_FUL,NULL))         HBS_AG_FUL 
 ,max(decode(LPARM,'PREGNANCY',LVALUE_FUL,NULL))         PREGNANT_FUL 
 ,max(decode(LPARM,'STOOL_GUAIAC',LVALUE_FUL,NULL))         STOOL_GUAIAC_FUL 
from PP_OC_OWNER.LBSRLBSR 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+) 
UNION
select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'PSA',LVALUE_FUL,NULL))          PSA_FUL 
 ,max(decode(LPARM,'CA125',LVALUE_FUL,NULL))          CA125_FUL 
 ,max(decode(LPARM,'CEA',LVALUE_FUL,NULL))          CEA_FUL 
 ,max(decode(LPARM,'CA19_9',LVALUE_FUL,NULL))          CA19_9_FUL 
 ,max(decode(LPARM,'CA15_3',LVALUE_FUL,NULL))          CA15_3_FUL 
 ,max(decode(LPARM,'CA27_29',LVALUE_FUL,NULL))          CA27_29_FUL 
 ,max(decode(LPARM,'AFP',LVALUE_FUL,NULL))          AFP_FUL 
 ,max(decode(LPARM,'HCG',LVALUE_FUL,NULL))          HCG_FUL 
 ,max(decode(LPARM,'HIV',LVALUE_FUL,NULL))          HIV_FUL 
 ,max(decode(LPARM,'HBS_AG',LVALUE_FUL,NULL))         HBS_AG_FUL 
 ,max(decode(LPARM,'PREGNANCY',LVALUE_FUL,NULL))         PREGNANT_FUL 
 ,max(decode(LPARM,'STOOL_GUAIAC',LVALUE_FUL,NULL))         STOOL_GUAIAC_FUL 
from PP_OC_OWNER.LBALLAB 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+)