select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'CALCIUM_URINE',LVALUE_FUL,NULL))          CALCIUM_FUL 
 ,max(decode(LPARM,'CHLORIDE_URINE',LVALUE_FUL,NULL))          CHLORIDE_FUL 
 ,max(decode(LPARM,'OSMOLALITY_URINE',LVALUE_FUL,NULL))          OSMOLALITY_FUL 
 ,max(decode(LPARM,'OXALATE_URINE',LVALUE_FUL,NULL))          OXALATE_FUL 
 ,max(decode(LPARM,'POTASSIUM_URINE',LVALUE_FUL,NULL))          POTASSIUM_FUL 
 ,max(decode(LPARM,'PROTEIN_ALBUMIN',LVALUE_FUL,NULL))          PROT_ALBUM_FUL 
 ,max(decode(LPARM,'PROTEIN_ALPHA_1',LVALUE_FUL,NULL))          PROT_ALPH1_FUL 
 ,max(decode(LPARM,'PROTEIN_ALPHA_2',LVALUE_FUL,NULL))          PROT_ALPH2_FUL 
 ,max(decode(LPARM,'PROTEIN_BETA',LVALUE_FUL,NULL))          PROT_BETA_FUL 
 ,max(decode(LPARM,'PROTEIN_GAMMA',LVALUE_FUL,NULL))         PROT_GAMMA_FUL 
 ,max(decode(LPARM,'SODIUM_URINE',LVALUE_FUL,NULL))         SODIUM_FUL 
 ,max(decode(LPARM,'UREA_NITROGEN_URINE',LVALUE_FUL,NULL))         UREA_NITRO_FUL 
 ,max(decode(LPARM,'URIC_ACID_URINE',LVALUE_FUL,NULL))         URIC_ACID_FUL 
from PP_OC_OWNER.LBOULBOU 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+) 
UNION
select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL 
from ( 
select 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE       SMPL_DT 
 ,DCMTIME       SMPL_TM 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID 
 ,max(decode(LPARM,'CALCIUM_URINE',LVALUE_FUL,NULL))          CALCIUM_FUL 
 ,max(decode(LPARM,'CHLORIDE_URINE',LVALUE_FUL,NULL))          CHLORIDE_FUL 
 ,max(decode(LPARM,'OSMOLALITY_URINE',LVALUE_FUL,NULL))          OSMOLALITY_FUL 
 ,max(decode(LPARM,'OXALATE_URINE',LVALUE_FUL,NULL))          OXALATE_FUL 
 ,max(decode(LPARM,'POTASSIUM_URINE',LVALUE_FUL,NULL))          POTASSIUM_FUL 
 ,max(decode(LPARM,'PROTEIN_ALBUMIN',LVALUE_FUL,NULL))          PROT_ALBUM_FUL 
 ,max(decode(LPARM,'PROTEIN_ALPHA_1',LVALUE_FUL,NULL))          PROT_ALPH1_FUL 
 ,max(decode(LPARM,'PROTEIN_ALPHA_2',LVALUE_FUL,NULL))          PROT_ALPH2_FUL 
 ,max(decode(LPARM,'PROTEIN_BETA',LVALUE_FUL,NULL))          PROT_BETA_FUL 
 ,max(decode(LPARM,'PROTEIN_GAMMA',LVALUE_FUL,NULL))         PROT_GAMMA_FUL 
 ,max(decode(LPARM,'SODIUM_URINE',LVALUE_FUL,NULL))         SODIUM_FUL 
 ,max(decode(LPARM,'UREA_NITROGEN_URINE',LVALUE_FUL,NULL))         UREA_NITRO_FUL 
 ,max(decode(LPARM,'URIC_ACID_URINE',LVALUE_FUL,NULL))         URIC_ACID_FUL 
from PP_OC_OWNER.LBALLAB 
GROUP BY 
  STUDY 
 ,DCMNAME 
 ,DCMSUBNM 
 ,SUBSETSN 
 ,DOCNUM 
 ,INVSITE 
 ,INV 
 ,PT 
 ,ACCESSTS 
 ,LOGINTS 
 ,LSTCHGTS 
 ,LOCKFLAG 
 ,CPEVENT 
 ,DCMDATE 
 ,DCMTIME 
 ,ACTEVENT 
 ,SUBEVENT_NUMBER 
 ,VISIT_NUMBER 
 ,QUALIFYING_VALUE 
 ,QUALIFYING_QUESTION 
 ,LAB 
 ,LABRANGE_SUBSET_NUMBER 
 ,LAB_ASSIGNMENT_TYPE_CODE 
 ,LAB_ID ) A, 
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B 
WHERE A.STUDY = B.STUDY (+) 
  AND A.PT = B.PT (+)