select A.*, NVL(B.PATIENT_FUL, A.PT) PATIENT_FUL, B.REG_INST_FUL
from (
SELECT * FROM (
select
       STUDY
      ,DCMNAME
      ,DCMSUBNM
      ,SUBSETSN
      ,DOCNUM
      ,INVSITE
      ,INV
      ,PT
      ,ACCESSTS
      ,LOGINTS
      ,LSTCHGTS
      ,LOCKFLAG
      ,CPEVENT
      ,DCMDATE      SMPL_DT
      ,DCMTIME      SMPL_TM
      ,ACTEVENT
      ,SUBEVENT_NUMBER
      ,VISIT_NUMBER
      ,QUALIFYING_VALUE
      ,QUALIFYING_QUESTION
      ,LAB
      ,LABRANGE_SUBSET_NUMBER
      ,LAB_ASSIGNMENT_TYPE_CODE
      ,LAB_ID
      ,PANEL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BENCE_JONES_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  BENCEJONES_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BENCE_JONES_URINE',LAB_RANGE_IND,NULL),NULL))  BENCEJONES_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'BENCE_JONES_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  BENCEJONES_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_A_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       IG_A_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_A_URINE',LAB_RANGE_IND,NULL),NULL))       IG_A_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_A_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       IG_A_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_D_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       IG_D_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_D_URINE',LAB_RANGE_IND,NULL),NULL))       IG_D_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_D_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       IG_D_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_E_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       IG_E_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_E_URINE',LAB_RANGE_IND,NULL),NULL))       IG_E_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_E_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       IG_E_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_G_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       IG_G_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_G_URINE',LAB_RANGE_IND,NULL),NULL))       IG_G_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_G_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       IG_G_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_M_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))       IG_M_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_M_URINE',LAB_RANGE_IND,NULL),NULL))       IG_M_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'IG_M_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))       IG_M_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'KAPPA_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))      KAPPA_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'KAPPA_URINE',LAB_RANGE_IND,NULL),NULL))      KAPPA_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'KAPPA_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))      KAPPA_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LAMBDA_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))     LAMBDA_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LAMBDA_URINE',LAB_RANGE_IND,NULL),NULL))     LAMBDA_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'LAMBDA_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))     LAMBDA_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MONOCLONAL_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  MONOCLONAL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MONOCLONAL_URINE',LAB_RANGE_IND,NULL),NULL))  MONOCLONAL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'MONOCLONAL_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  MONOCLONAL_GRADE_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYCLONAL_URINE',SUBSTR(LVALUE_FUL, 1, 20),NULL),NULL))  POLYCLONAL_FUL
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYCLONAL_URINE',LAB_RANGE_IND,NULL),NULL))  POLYCLONAL_RANG_IND
      ,max(DECODE(PANEL,0, DECODE(LPARM_FUL,'POLYCLONAL_URINE',SUBSTR(CTC_GRADE_FUL, 1, 20),NULL),NULL))  POLYCLONAL_GRADE_FUL
 from (
        SELECT A.*, NVL(B.PANEL, 0) PANEL
          FROM PP_OC_OWNER.LBALLAB A,
               (SELECT DISTINCT OC_LAB_QUESTION, PANEL
                  FROM NCI_LABTEST_MAPPING
                 WHERE FILE_ID IS NOT NULL
                   AND FIELD_NAME IS NOT NULL
                   AND OC_LAB_QUESTION IS NOT NULL
                   AND (OC_STUDY = 'ALL' OR OC_STUDY = 'THER_STD' )  ) B
         WHERE A.LPARM = B.OC_LAB_QUESTION
        )
 GROUP BY
      STUDY
     ,DCMNAME
     ,DCMSUBNM
     ,SUBSETSN
     ,DOCNUM
     ,INVSITE
     ,INV
     ,PT
     ,ACCESSTS
     ,LOGINTS
     ,LSTCHGTS
     ,LOCKFLAG
     ,CPEVENT
     ,DCMDATE
     ,DCMTIME
     ,ACTEVENT
     ,SUBEVENT_NUMBER
     ,VISIT_NUMBER
     ,QUALIFYING_VALUE
     ,QUALIFYING_QUESTION
     ,LAB
     ,LABRANGE_SUBSET_NUMBER
     ,LAB_ASSIGNMENT_TYPE_CODE
     ,LAB_ID
     ,PANEL )
  WHERE 
        BENCEJONES_FUL IS NOT NULL
     OR IG_A_FUL IS NOT NULL
     OR IG_D_FUL IS NOT NULL
     OR IG_E_FUL IS NOT NULL
     OR IG_G_FUL IS NOT NULL
     OR IG_M_FUL IS NOT NULL
     OR KAPPA_FUL IS NOT NULL
     OR LAMBDA_FUL IS NOT NULL
     OR MONOCLONAL_FUL IS NOT NULL
     OR POLYCLONAL_FUL IS NOT NULL ) A,
  PP_EXT_OWNER.CTS_PTID_ENRL_VW B
WHERE A.STUDY = B.STUDY (+)
  AND A.PT = B.PT (+)